spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_local
    username: user_local
    password: password_local
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  access-token:
    duration: PT30M
    secret: access_token_secret
  refresh-token:
    duration: P7D
    secret: refresh_token_secret

argon2:
  salt-length: 32
  hash-length: 16
  parallelism: 4
  memory: 65536
  iterations: 1
