version: "3.9"
services:
  db-local:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=db_local
      - POSTGRES_USER=user_local
      - POSTGRES_PASSWORD=password_local
    ports:
      - "5432:5432"
    volumes:
      - dblocal:/var/lib/postgresql/data
  db-test:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=user_test
      - POSTGRES_PASSWORD=password_test
    ports:
      - "5433:5433"
    volumes:
      - dbtest:/var/lib/postgresql/data
volumes:
  dblocal:
  dbtest:
